# --- 1. external HTTP /healthz ---
apiVersion: v1
kind: Service
metadata:
  name: sort-service
spec:
  type: ClusterIP
  selector:
    app: sort-service
  ports:
    - name: http
      port: 80
      targetPort: 4002
---
# --- 2. in-cluster raw TCP ---
apiVersion: v1
kind: Service
metadata:
  name: sort-service-tcp
spec:
  clusterIP: None
  selector:
    app: sort-service
  ports:
    - name: tcp-micro
      port: 5002
      targetPort: 5002
